[tool.poetry]
name = "metricity"
version = "1.3.1"
description = "Advanced metric collection for the Python Discord server"
authors = ["Joe Banks <joseph@josephbanks.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.8 || ~3.9"
"discord.py" = {url = "https://github.com/Rapptz/discord.py/archive/master.zip"}
deepmerge = "^0.1.0"
toml = "^0.10.1"
coloredlogs = "^14.0"
python-dotenv = "^0.14.0"
gino = "^1.0.1"
alembic = "^1.4.2"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
flake8-annotations = "^2.3.0"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"

[tool.poetry.scripts]
start = "metricity.__main__:start"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
